import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API="http://127.0.0.1:8000";const money=n=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(n);
function Badge({level}){return <span className={"badge "+level.toLowerCase()}>{level}</span>}
function App(){const[d,setD]=useState(),[ps,setPs]=useState([]),[sel,setSel]=useState(),[search,setSearch]=useState(""),[sector,setSector]=useState("All"),[role,setRole]=useState("Management"),[q,setQ]=useState(""),[ans,setAns]=useState("");
const load=async()=>{const[a,b]=await Promise.all([fetch(API+"/api/dashboard").then(r=>r.json()),fetch(API+"/api/projects").then(r=>r.json())]);setD(a);setPs(b);setSel(b[0])};useEffect(()=>{load().catch(console.error)},[]);
const sectors=useMemo(()=>["All",...new Set(ps.map(p=>p.sector))],[ps]);const list=ps.filter(p=>(sector==="All"||p.sector===sector)&&`${p.project_id} ${p.project_name} ${p.ministry} ${p.state}`.toLowerCase().includes(search.toLowerCase()));const ask=async()=>{if(q){setAns((await fetch(API+"/api/assistant?q="+encodeURIComponent(q)).then(r=>r.json())).answer)}};if(!d)return <div className="loading">●<h2>Loading Project Intelligence…</h2></div>;
return <div className="shell"><aside><div className="brand"><div className="logo">P</div><div><b>PAIMANA</b><small>Predictive Intelligence</small></div></div><nav><a className="active">◈ Dashboard</a><a>▣ Projects</a><a>⚠ Early Warnings</a><a>◉ Analytics</a><a>◎ Reports</a></nav><div className="side"><b>SIH26103</b><span>Smart Automation</span><small>Predictive + Prescriptive Monitoring</small></div></aside>
<main><header><div><span className="crumb">PROJECT MONITORING / OVERVIEW</span><h1>Infrastructure Command Center</h1><p>Predict risks early. Understand the drivers. Take action.</p></div><div className="head"><select value={role}onChange={e=>setRole(e.target.value)}><option>Management</option><option>Project Officer</option><option>Admin</option></select><div className="user">● {role}</div></div></header>
<section className="hero"><div><span>JULY 2026 • PORTFOLIO INTELLIGENCE</span><h2>From monitoring to <em>early action.</em></h2><p>AI-ready analytics for cost, progress and implementation risk.</p></div><div className="heroStat"><b>{d.early_warnings}</b><span>early warnings</span></div></section>
<section className="kpis"><K t="Projects monitored"v={d.total_projects}i="▦"/><K t="High risk"v={d.high_risk}i="!" c="alert"/><K t="Original portfolio cost"v={"₹"+money(d.original_cost_crore)}i="₹"/><K t="Average physical progress"v={d.average_progress+"%"}i="↗"/></section>
<section className="grid"><div className="panel"><div className="ph"><div><h2>Project Risk Register</h2><p>Search and prioritise projects requiring intervention.</p></div><button onClick={load}>↻ Refresh</button></div><div className="filters"><input placeholder="⌕  Search project, ministry, state…"value={search}onChange={e=>setSearch(e.target.value)}/><select value={sector}onChange={e=>setSector(e.target.value)}>{sectors.map(x=><option key={x}>{x}</option>)}</select></div><div className="table"><table><thead><tr><th>Project</th><th>Sector</th><th>Progress</th><th>Cost</th><th>Risk</th></tr></thead><tbody>{list.map(p=><tr key={p.project_id}onClick={()=>setSel(p)}className={sel?.project_id===p.project_id?"chosen":""}><td><b>{p.project_name}</b><small>{p.project_id} • {p.ministry}</small></td><td>{p.sector}</td><td><div className="progress"><i style={{width:Math.min(100,p.physical_progress_pct)+"%"}}/></div><small>{p.physical_progress_pct}%</small></td><td>{p.cost_escalation_pct>0?"+"+p.cost_escalation_pct+"%":"No change"}</td><td><Badge level={p.risk_level}/><small>{p.risk_score}/100</small></td></tr>)}</tbody></table></div></div>
{sel&&<div className="panel detail"><div className="ph"><div><span className="pid">{sel.project_id}</span><h2>{sel.project_name}</h2></div><Badge level={sel.risk_level}/></div><div className="risk"><div><small>Predictive attention score</small><strong>{sel.risk_score}<span>/100</span></strong></div><div className="circle">{sel.risk_level}</div></div><div className="mini">{[["Original cost","₹"+money(+sel.original_cost_crore)+" Cr"],["Revised cost","₹"+money(+sel.revised_cost_crore)+" Cr"],["Expenditure","₹"+money(+sel.expenditure_crore)+" Cr"],["Physical progress",sel.physical_progress_pct+"%"]].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><h3>Risk drivers</h3><div className="chips">{sel.drivers.map(x=><span>• {x}</span>)}</div><h3>Recommended actions</h3><ul>{sel.recommendations.map(x=><li>✓ {x}</li>)}</ul><div className="note">Source: uploaded PAIMANA Flash Report July 2026. Risk score is a prototype analytical indicator, not an official PAIMANA score.</div></div>}</section>
<section className="bottom"><div className="panel assistant"><span className="ai">PROJECT INTELLIGENCE ASSISTANT</span><h2>Ask the portfolio</h2><p>Get instant answers from the monitoring dataset.</p><div className="ask"><input value={q}onChange={e=>setQ(e.target.value)}onKeyDown={e=>e.key==="Enter"&&ask()}placeholder="Which projects are high risk?"/><button onClick={ask}>Ask AI</button></div>{ans&&<div className="answer">✦ {ans}</div>}</div><div className="panel"><div className="ph"><div><h2>Early warnings</h2><p>Prioritised intervention queue</p></div><span className="live">● LIVE</span></div>{ps.filter(p=>p.risk_level!=="Low").slice(0,6).map(p=><div className="warning"onClick={()=>setSel(p)}><Badge level={p.risk_level}/><div><b>{p.project_id} · {p.project_name}</b><small>{p.drivers[0]}</small></div><strong>{p.risk_score}</strong></div>)}</div></section><footer>SIH26103 Prototype • Green & White Analytics Theme • July 2026 PAIMANA project records</footer></main></div>}
function K({t,v,i,c}){return <div className="kpi"><div className={"icon "+(c||"")}>{i}</div><span>{t}</span><b>{v}</b><small>Portfolio indicator</small></div>}createRoot(document.getElementById("root")).render(<App/>);